asset_host: http://localhost:8080
sketches_host: https://quintype-demo.quintype.io
host_to_automatic_api_host:
  - ".lvh.me"
publisher_theme:
  ace:
    monogram: https://fea.assettype.com/quintype/assets/logo-b6438210bc.svg
    logo: https://svgshare.com/i/5Qv.svg
    primary_color: "#2f73e4"
    secondary_color: "#a3a3a3"
    header_text_color: "#404040"
    header_background_color: "#FFF"
    footer_text_color: "#FFF"
    footer_background_color: "#000"
    dfp_network_id: '60988533'
  quintype-demo:
    monogram: ""
    logo: ""
    primary_color: "#000"
    secondary_color: ""
    header_text_color: ""
    header_background_color: ""
    footer_text_color: ""
    footer_background_color: ""
    dfp_network_id: '60988533'
  samachara:
    monogram: https://fea.assettype.com/quintype/assets/logo-b6438210bc.svg
    logo: https://svgshare.com/i/5Qv.svg
    primary_color: "#2f73e4"
    secondary_color: "#a3a3a3"
    header_text_color: "#404040"
    header_background_color: "#FFF"
    footer_text_color: "#FFF"
    footer_background_color: "#000"
    dfp_network_id: '60988533'
    static_pages: ['aboutUs', 'privacyPolicy', 'contactUs']
    amp_logo:
      src: https://images.assettype.com/samachara/2018-03/a9131129-1db7-462c-8b42-cc960d30ed50/74258cd2-9246-4d11-8b46-da4227ffa05e.jpg
      type: image/jpeg
  abpnews:
    monogram: https://fea.assettype.com/quintype/assets/logo-b6438210bc.svg
    logo: https://svgshare.com/i/5Qv.svg
    primary_color: "#2f73e4"
    secondary_color: "#a3a3a3"
    header_text_color: "#404040"
    header_background_color: "#FFF"
    footer_text_color: "#FFF"
    footer_background_color: "#000"
    dfp_network_id: '60988533'
