asset_host: http://localhost:8080
sketches_host: https://ace.staging.quintype.io
host_to_automatic_api_host:
  - "-web"
  - ".malibu"
publisher_theme:
  ace:
    monogram: https://fea.assettype.com/quintype/assets/logo-b6438210bc.svg
    logo: https://svgshare.com/i/5Qv.svg
    primary_color: "#000"
  quintype-demo:
    monogram: ""
    logo: ""
    primary_color: "#000"
  network18:
    monogram: ""
    logo: ""
    primary_color: "#ccc"
